ddzproject:
  email:
    host: smtp.qq.com # 邮箱服务器地址
    port: 465 # 邮箱服务器端口
    username: ###
    password: ###
    protocol: smtp
  datasource:
    url: jdbc:mysql://localhost:3306/ddzproject?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      database: 0
  backend:
    message: 123你你你
